server:
  port: 8083  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  

  
spring:
  application:
    name: API-GATEWAY
        
    
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**
          
          
      - id: VACCINATION-CENTER-SERVICE  
        uri:
           lb://VACCINATION-CENTER-SERVICE
        predicates:
        - Path=/center/** 
           
    


    
           
          
          
          
          
     
      